export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Learn Hacking",
  headline: "Learn How to Hack",
  description: "Everything you need to know ",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Courses offered",
  headline: "Choose as per your requirements",
  description: "Courses are provided to you as per your requirements",
  buttonLabel: "Get Started",
  imgStart: true,
  img: require("../../images/svg-2.svg"),
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
};
export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Sign Up",
  headline: "Get Started Quickly",
  description: "Let's Begin Hacking",
  buttonLabel: "Start Now",
  imgStart: false,
  img: require("../../images/svg-3.svg"),
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
};
